Events page added
csdu/sankalan pull request #5
Opened 2019-12-25 09:49 UTC by bmegha98

2019-12-25 09:56 UTC, rumansaleem commented
we need to list all the events on the event page as well. Moreover, you should use a sperate layout that extends base layout for events, which will make use of the yaml variables, such as image, title etc.

2019-12-25 12:00 UTC, bmegha98 commented
Ya i have done that in event.ejs file by making use of image variable

2019-12-25 17:18 UTC, rumansaleem commented
But it is not reflected on the event's page (for example: on `/events/alacrity`), and what about the listing of events on `/events` page.

2019-12-25 17:43 UTC, rumansaleem requested changes
Please make the suggested changes and make sure your build lists all the events on the listings page and they are properly linked to the each event's page. Also, make sure event page shows posters.

2019-12-25 17:43 UTC, rumansaleem commented on pages/events/codingclub.md
> +permalink : /events/Coding Club/
it should be sluggish cased (all lowercase, words separated by a hyphen), `/events/coding-club`

2019-12-25 17:43 UTC, rumansaleem commented on pages/events/chakravyuh.md
> +permalink : /events/Chakravyuh/
make sure all the permalinks are lower cased and words separated by hyphens.

2019-12-25 17:43 UTC, rumansaleem commented on pages/events/brainspark.md
> +tags: ["event"]
you can add tags like, "puzzle", "mind game" for now it doesn't matter. But you got the idea.

2019-12-25 17:43 UTC, rumansaleem commented on _includes/events.ejs
> +                <% events.forEach(function(event){ %>
seems like it doesn't work, or the zeit didnt built this correctly.

2019-12-25 17:43 UTC, rumansaleem commented on _includes/events.ejs
> +                    "We have 9 technical events as well as 7 non-technical events."
make these counts dynamic, use a front-matter boolean variable `technical` for all events, filter the array of events and display their counts dynamically. You can also segregate the technical and non-technical events in the listings.

2019-12-25 17:43 UTC, rumansaleem commented on _includes/events.ejs
> +pagination:
I don't think pagination is required here... We would list all the events on the same page they are no more than 25 (though they are only 8-10). Its completely fine to list them all.

2019-12-25 17:43 UTC, rumansaleem commented on pages/events/alfaaz.md
> +permalink : /events/Alfaaz_Aur_Jazbaat/
make it `/alfaaz-aur-jazbaat`

2019-12-25 17:43 UTC, rumansaleem commented on pages/events/codingclub.md
> +title : CodingClub
I think its coding "cup", and you should add a space here.

2019-12-27 10:01 UTC, bmegha98 commented
Krishna told us that some of the events might get combined so for now i have listed only few events and can later change the events accordingly and how do i list all events on particular event page. All the events will be listed on main event page no?

2019-12-28 11:26 UTC, rumansaleem commented
@bmegha98 It's okay you can change events later. But right now I cannot see any events listed on `/events` page. Here is a screenshot of the `/events` page on build environment:

![sankalan-2020-events-page](https://user-images.githubusercontent.com/25204498/71542937-f3c59e00-2992-11ea-8232-f2eadcb5c792.png)

2019-12-28 11:33 UTC, bmegha98 commented
How's it possible :|
It's working on my system 
Will look into this

2019-12-28 12:04 UTC, rumansaleem commented
if its working on your system, then maybe there's some problem with the Zeit's build. Let me test this locally on my system.

2019-12-28 12:09 UTC, bmegha98 commented
Ohkay
Will make other changes

2019-12-28 12:22 UTC, rumansaleem commented
Please refer to the previous reply.

2019-12-28 13:32 UTC, rumansaleem commented
there should be a poster displayed on the event page as well, right now its empty.
![Screenshot from 2019-12-28 19-09-04](https://user-images.githubusercontent.com/25204498/71544349-625f2780-29a4-11ea-9a0a-fb6d2c851aac.png)

2019-12-28 13:32 UTC, rumansaleem approved these changes

2019-12-28 13:34 UTC, bmegha98 commented
yess ! i haven't made layout for event pages yet

2019-12-28 13:36 UTC, rumansaleem commented
okay let's keep it here, I'm merging these changes. But start working on responsiveness.

2019-12-28 13:37 UTC, merged